# Generated by Django 4.1 on 2022-08-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_alter_entry_created_at_alter_entry_update_on"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entry",
            old_name="update_on",
            new_name="updated_on",
        ),
    ]
